In [1]:
import jupy_helpers

# Numpy = (fast) numerical Python

https://www.numpy.org says:
> NumPy is the fundamental package for scientific computing with Python. It contains among other things:
> 
> * a powerful N-dimensional array object
> * sophisticated (broadcasting) functions
> * tools for integrating C/C++ and Fortran code
> * useful linear algebra, Fourier transform, and random number capabilities

## Why Numpy?

Because numerics using only Python standard library is cumbersome and in most cases slow.

In [2]:
import numpy as np

In [3]:
np.__version__

'1.16.4'

The most used type is `np.ndarray`, which is often created by `np.array`.

In [7]:
array = np.array([0, 2., 5])
array

array([0., 2., 5.])

In [8]:
type(array)

numpy.ndarray

Unlike built-in containers like `list`s, `np.ndarray`s have
* homogeneous `dtype`(s) (data types)

In [9]:
array.dtype

dtype('float64')

* fixed `shape` (dimensions)

In [10]:
array.shape

(3,)

**Exercise:** Can you fill the missing values (by replacing `...`) to make the `assert`s pass (i.e. no `AssertException` raised)?

In [11]:
test_array = np.array([[1.9, 2.8], [3.7, 4.5]])
test_array

array([[1.9, 2.8],
       [3.7, 4.5]])

In [18]:
%exercise

test_array_shape = (2, 2)
test_array_dtype = np.float64

In [19]:
%validate

assert test_array.shape == test_array_shape
assert test_array.dtype == test_array_dtype

Arrays can be created using helper constructors, such as `empty`, `zeros`, `arange`, `linspace`, `diag`, ...

In [20]:
np.zeros((2, 8), dtype=float)

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [21]:
np.linspace(-1, 1, 5)

array([-1. , -0.5,  0. ,  0.5,  1. ])

**Exercise:** Explore what values are in a new `empty` array and try to explain.

In [34]:
%exercise

np.empty((5, 2))

array([[4.64016758e-310, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [2.22809558e-312, 6.40440406e+170],
       [4.99045473e+174, 4.22007947e-090],
       [1.04811176e+165, 8.38851587e-315]])

### Supported dtypes

- boolean 
- integers (8-, 16-, 32-, 64-bit), unsigned / signed
- float (32-, 64-bit)
- complex
- fixed-length strings (byte / unicode)
- object (~ pointers to any Python object)
- structured types (with more fields)

For more details, see https://docs.scipy.org/doc/numpy/user/basics.types.html and https://docs.scipy.org/doc/numpy/reference/arrays.dtypes.htm

In [35]:
string_array = np.array(["a", "aardvark", "abe"])
string_array.dtype

dtype('<U8')

In [36]:
string_array = np.array(["a", "aardvark", "abe"], dtype="object") 
string_array.dtype

dtype('O')

## Buffer protocol

`ndarray` data are stored in (typically) contiguous memory blocks. This is for performance reasons because Numpy can employ fast C libraries (like BLAS) for vectorized operations without converting and / or rearranging the data in the memory. Python offers built-in [Buffer Protocol](https://docs.python.org/3/c-api/buffer.html#bufferobjects) which standardizes this approach and enables (relatively) easy integration with C libraries.

In a nutshell, `ndarray` data are described by their memory buffer location (pointer), and some metedata mainly describing the data type (`typestr`) and dimensionality (`shape` and `strides`).

Looking a bit under the hood, we can see the buffer info by `info` or `flags`

In [37]:
np.info(array)

class:  ndarray
shape:  (3,)
strides:  (8,)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  True
data pointer: 0x556aff443170
byteorder:  little
byteswap:  False
type: float64


In [38]:
array.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

This is an implementation detail, although very important because it determines fundamental advantages, limitations and best practices for using `numpy`.

## Indexing

Numpy supports enhanced indexing compared e.g. to Python's `list` or `array` types. Especially:
* multiple dimensions
* enhaced slices
* "advanced" or "fancy" indexing using arrays

In [39]:
array_1d = np.arange(0, 10)
array_1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Basic indexing 

Basic indexing and slicing on 1D array works identically to lists:

In [40]:
array_1d[5]

5

In [47]:
array_1d[5: -1]

array([5, 6, 7, 8])

In [44]:
array_1d[::-3]

array([9, 6, 3, 0])

**Exercise:** Fill the slicing to satisfy the assert test. Notice we have to use `np.all` because the result is an array which cannot be converted to a single boolean value unambigously (is a true and false couple true or false?).

In [48]:
%exercise

result = array_1d[1::4]
result

array([1, 5, 9])

In [49]:
%validate

assert np.all(result == np.array([1, 5, 9]))

In [51]:
array_1d[...]    # thre dots means ellipsis

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

*Extra question:* Did you notice that (and how) the ellipsis slice `[...]` actually work?

Multi-dimensional arrays can be index conveniently:

In [52]:
array_2d = np.random.randint(0, 10, (2, 6))
array_2d

array([[6, 9, 1, 1, 9, 7],
       [4, 9, 0, 4, 1, 8]])

In [53]:
array_3d = array_2d.reshape(2, -1, 3)
array_3d

array([[[6, 9, 1],
        [1, 9, 7]],

       [[4, 9, 0],
        [4, 1, 8]]])

Single index returns a slice in one dimension:

In [54]:
array_2d[1]

array([4, 9, 0, 4, 1, 8])

Which is equivalent to:

In [55]:
array_2d[1, :]

array([4, 9, 0, 4, 1, 8])

And also

In [56]:
array_2d[1, ...]

array([4, 9, 0, 4, 1, 8])

Examples for 3-D array:

In [57]:
array_3d[:, 0, 1:]

array([[9, 1],
       [9, 0]])

In [58]:
array_3d[..., -1]

array([[1, 7],
       [0, 8]])

### Fancy indexing

Suppose you need to access particular elements, say `3, 0, 5`. Instead of something like `np.array([array_1d[3], array_1d[0], array_1d[5]])`, you can write

In [59]:
array_1d[[3, 0, 5]]

array([3, 0, 5])

**Exercise:** Use (fancy) indexing to create a 8 x 8 chess-board pattern (0 / 1 in place of white / black) from a uniform array.

In [61]:
chess_board = np.ones((8, 8), dtype=int)
chess_board

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

In [112]:
%exercise

chess_board = np.ones((8, 8), dtype=int)

chess_board[1::2, ::2] = 0
chess_board[::2, 1::2] = 0

# display
chess_board

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

In [113]:
%validate

assert np.all(chess_board == np.tile([[1, 0], [0, 1]], (4, 4)))

Another possibility is to use arrays of boolean values for slicing.

In [82]:
bool_indexes = np.zeros_like(array_1d, dtype=bool)
bool_indexes[[2, 5]] = True
bool_indexes

array([False, False,  True, False, False,  True, False, False, False,
       False])

In [83]:
array_1d[bool_indexes]

array([2, 5])

### Indexing vs. copying

Indexing in `numpy` does not have to create copies. Data copy is created only when inevitable.

Hence, **modyfying a slice can modify the original array**.

In [84]:
original_array = np.linspace(0, 1, 3)
original_array

array([0. , 0.5, 1. ])

In [85]:
array_slice = original_array[1: ]
array_slice *= 2
array_slice

array([1., 2.])

In [87]:
original_array

array([0., 1., 2.])

See that??? The original array has been modified.

## Vector operations

Numpy is optimized for performance. One of the key ingredient are vectorized operations: Instead of (slow) looping by elements, an operation can be performed on the whole or at least a subset of an array.

Let's try to implement a dot product (1D for simplicity):

In [88]:
def dot(x, y):
    result = 0
    for i, j in zip(x, y):
        result += i * j
    
    return result

In [89]:
x = np.random.sample((4, ))
y = np.random.sample((4, ))

dot(x, y)

1.1643175467816693

In [93]:
x, y

(array([0.8390096 , 0.63642771, 0.94044063, 0.79309947]),
 array([0.77118414, 0.16998079, 0.11914461, 0.37455294]))

Test our function using `allclose` to compare floats only up to certain precision.

In [91]:
assert np.allclose(dot(x, y), x.dot(y))

We can compare the performance (on larger arrays)

In [95]:
size = (1000, )
x_large = np.random.sample(size)
y_large = np.random.sample(size)

In [96]:
%timeit dot(x_large, y_large)

354 µs ± 10.4 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [97]:
%timeit x_large.dot(y_large)

569 ns ± 10.4 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


Even multiplacation (`*` is element-wise is Numpy) is vectorized. E.g.:

In [98]:
x * y

array([0.6470309 , 0.10818048, 0.11204843, 0.29705774])

**Exercise:** Implement dot using `*` and `sum` and measure its performace using `%timeit`.

In [114]:
%exercise

def dot_2(x, y):
    return np.sum(x * y)

In [115]:
%validate

assert np.allclose(dot_2(x, y), x.dot(y))

In [116]:
%timeit dot_2(x_large, y_large)

5.08 µs ± 58.4 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


Bottom line: use numpy functions and operations because they are vectorized and hence (in most cases) faster.

## Broadcasting

Numpy automatically broadcasts (aligns / enhances the dimensions) of arrays if it "makes sense" (there are strict rules :). Broadcasting simplifies operations and can make them faster and / or less memory consuming.

An example is to substract the column mean from an $n \times m$ array.

In [118]:
X = np.linspace(0, 1, 15).reshape(-1, 3)
X, X.shape

(array([[0.        , 0.07142857, 0.14285714],
        [0.21428571, 0.28571429, 0.35714286],
        [0.42857143, 0.5       , 0.57142857],
        [0.64285714, 0.71428571, 0.78571429],
        [0.85714286, 0.92857143, 1.        ]]), (5, 3))

In [120]:
X.mean(axis=0)

array([0.42857143, 0.5       , 0.57142857])

Now we'd like to center the columns around zero, i.e. make the mean = 0 of all columns.

In [123]:
X_centered = X - X.mean(axis=0)    # it automatically expand the shape of the second term (repetition)
X_centered

array([[-4.28571429e-01, -4.28571429e-01, -4.28571429e-01],
       [-2.14285714e-01, -2.14285714e-01, -2.14285714e-01],
       [ 0.00000000e+00,  1.11022302e-16,  0.00000000e+00],
       [ 2.14285714e-01,  2.14285714e-01,  2.14285714e-01],
       [ 4.28571429e-01,  4.28571429e-01,  4.28571429e-01]])

In [124]:
X_centered.mean(axis=0)

array([0.00000000e+00, 6.66133815e-17, 2.22044605e-17])

We can also do this explicitely with `newaxis`

In [126]:
X_centered = X - X.mean(axis=0)[np.newaxis, :]
X_centered

array([[-4.28571429e-01, -4.28571429e-01, -4.28571429e-01],
       [-2.14285714e-01, -2.14285714e-01, -2.14285714e-01],
       [ 0.00000000e+00,  1.11022302e-16,  0.00000000e+00],
       [ 2.14285714e-01,  2.14285714e-01,  2.14285714e-01],
       [ 4.28571429e-01,  4.28571429e-01,  4.28571429e-01]])

Pandas uses broadcasting internally for many operations. That's for example why you should reserve some space in you RAM (around 3 - 5 times the dataset size), for a flawless Pandas data processing experience.

**Exercise:** Calculate $uv$ for random 1D arrays $u$ and $v$, defined as $(uv)_{ij} = u_i v_j$, using broadcasting.

In [ ]:
%exercise

u = np.random.sample((3, ))
v = np.random.sample((5, ))

uv = u[...] * v[...]

In [ ]:
%validate

for i, j in zip(range(u.size), range(v.size)):
    assert uv[i, j] == u[i] * v[j]